trigger:
- master 

pool:
  vmImage: ubuntu-latest

variables:
  acr-servcon: ''
  docker-servcon: ''

jobs:
- job: Checkout
  steps:
    

- job: SonarQube
  
  step:
  # Prepare Analysis Configuration task
  - task: SonarQubePrepare@6
    displayName: 'SonarQube code analysis'
    inputs:
      SonarQube: 'YourSonarqubeServerEndpoint'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'YourProjectKey' 

- job: Quality gate
  dependsOn: SonarQube
  steps:
  # Run Code Analysis task
  - task: SonarQubeAnalyze@6
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  # Publish Quality Gate Result task
  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'


- job: Dependencies
  
  steps:
  # npm v1
  # Install and publish npm packages
  - task: Npm@1
    displayName: 'install and publish dependencies'
    inputs:
      command: 'install' 
      workingDir: '.'
       
     
- job: OWASP
  steps:


- job: Trivy FS  
  steps:
  - task: trivy@1
    inputs:
      path: .

- job: Build n Push
  steps:
  - task : Docker@2
    inputs:
      containerRegistry: $acr-servcon
      command: 'login'

  - task : Docker@2
    inputs:
      containerRegistry: $docker-servcon
      command: 'login'

  # Build docker image
  - task: Docker@2
    inputs:  
      containerRegistry:  
      command: 'build'      
      Dockerfile: '**/Dockerfile'
      #buildContext: '**' 
      repository: |
      'app/netflixApp'
      'beeygold/netflixApp'

  - task: Docker@2
    inputs:  
      containerRegistry: 
      #repository: # repository  
      command: 'push' 
      
    
- job: Scan Image
  steps:
  - task: trivy@1
    inputs:
      image: beeygold/netflixApp

- job: Deploy 

- job: Deploy k8s     



